deployment:
  controlplaneCluster:
    appName: "loki"
    chartName: "loki-stack"
    chartRepo: "https://kube-tarian.github.io/helmrepo-supporting-tools"
    version: "0.0.3"
    defaultNamespace: "observability"
    privilegedNamespace: true
    valuesFile: "values.yaml"
capabilities:
  - deploy-controlplane-cluster
