credentials:
  - name: "natsToken"
    type: "randomKey"
    vaultSecretPath: "generic/nats/auth-token"
    vaultSecretKeys:
      - token
    secrertName: "nats-token"
    helmValueSecretKey: "natsTokenSecretName"
