deployment:
  controlplaneCluster:
    appName: "kubviz-client"
    chartName: "client"
    chartRepo: "https://intelops.github.io/kubviz/"
    version: "1.1.26"
    defaultNamespace: "observability"
    privilegedNamespace: true
    valuesFile: "values.yaml"
capabilities:
  - deploy-controlplane-cluster
  - generate-credentials
