nats:
  service:
    type: NodePort
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 200m
      memory: 350Mi
  auth:
    secret:
      name: "{{ .natsTokenSecretName }}"
      key: "token"
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 200m
    memory: 150Mi
